from telebot import types

markup1 = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/help")
item2 = types.KeyboardButton("/numbers")
item3 = types.KeyboardButton("/description")
item4 = types.KeyboardButton("/update")
item5 = types.KeyboardButton("/exit")
markup1.add(item1, item2, item3, item4, item5)

markup2 = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/help")
item2 = types.KeyboardButton("/numbers")
item3 = types.KeyboardButton("/update")
item4 = types.KeyboardButton("/description")
item5 = types.KeyboardButton("/exit")
markup2.add(item1, item2, item3, item4, item5)

markup3 = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("101")
item2 = types.KeyboardButton("102")
item3 = types.KeyboardButton("103")
item4 = types.KeyboardButton("104")
item5 = types.KeyboardButton("112")
item6 = types.KeyboardButton("/help")
item7 = types.KeyboardButton("/exit")
markup3.add(item1, item2, item3, item4, item5, item6, item7)

markup4 = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/reg")
item2 = types.KeyboardButton("/exit")
markup4.add(item1, item2)

markup5 = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/start")
item2 = types.KeyboardButton("/help")
markup5.add(item1, item2)

markup6 = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/help")
item2 = types.KeyboardButton("/description")
item3 = types.KeyboardButton("/exit")
markup6.add(item1, item2, item3)

markup7 = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
item1 = types.KeyboardButton("Место проживания")
item2 = types.KeyboardButton("Место учёбы")
item3 = types.KeyboardButton("Место работы")
item4 = types.KeyboardButton("/exit")
markup7.add(item1, item2, item3, item4)
