from telebot import types

StartMenu = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/help")
item2 = types.KeyboardButton("/numbers")
item3 = types.KeyboardButton("/description")
item4 = types.KeyboardButton("/update")
item5 = types.KeyboardButton("/exit")
StartMenu.add(item1, item2, item3, item4, item5)

HelpMenu = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/help")
item2 = types.KeyboardButton("/numbers")
item3 = types.KeyboardButton("/update")
item4 = types.KeyboardButton("/description")
item5 = types.KeyboardButton("/exit")
HelpMenu.add(item1, item2, item3, item4, item5)

NumbersMenu = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("101")
item2 = types.KeyboardButton("102")
item3 = types.KeyboardButton("103")
item4 = types.KeyboardButton("104")
item5 = types.KeyboardButton("112")
item6 = types.KeyboardButton("/help")
item7 = types.KeyboardButton("/exit")
NumbersMenu.add(item1, item2, item3, item4, item5, item6, item7)

FirstConnectMenu = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/reg")
item2 = types.KeyboardButton("/exit")
FirstConnectMenu.add(item1, item2)

ExitMenu = types.ReplyKeyboardMarkup(resize_keyboard=True)
item1 = types.KeyboardButton("/start")
item2 = types.KeyboardButton("/help")
ExitMenu.add(item1, item2)

RegistrationMenu = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
item1 = types.KeyboardButton("Место проживания")
item2 = types.KeyboardButton("Место учёбы")
item3 = types.KeyboardButton("Место работы")
item4 = types.KeyboardButton("/exit")
RegistrationMenu.add(item1, item2, item3, item4)

EmergencyMailingMenu = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
item1 = types.KeyboardButton("Да")
item2 = types.KeyboardButton("Нет")
EmergencyMailingMenu.add(item1, item2)

AdminMenu= types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
item1 = types.KeyboardButton("Войти")
item2 = types.KeyboardButton("/exit")
AdminMenu.add(item1, item2)